name: make-install

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  make-install-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make-install
      run: make install
    - name: make-diff-check
      run: make diff-check
  make-install-ubuntu-1804:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: make-install
      run: make install
    - name: make-diff-check
      run: make diff-check
  make-install-macos-latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: make-install
      run: make install
    - name: make-diff-check
      run: make diff-check
