name: Static source code analysis

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installing the shellcheck tool
      run: |
        scversion="stable"
        wget -qO- "https://github.com/koalaman/shellcheck/releases/download/${scversion?}/shellcheck-${scversion?}.linux.x86_64.tar.xz" | tar -xJv
        sudo cp "shellcheck-${scversion}/shellcheck" /usr/bin/
        shellcheck --version
    - name: Running checks
      run: make check
